version: '3'

services:
  pdf-markdown-service:
    build: .
    ports:
      - "8239:8239"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
